# .readthedocs.yaml
version: 2

# Build documentation with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

# Set the Python version and requirements
python:
  version: "3.10"
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
  system_packages: true

# Enable PDF and ePub builds
formats: ["pdf", "epub"]
